name: remember_me
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts:
  heroicons:
  flutter_svg:
  table_calendar: 
  flutter_colorpicker:
  sp_util:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 
  flutter_native_splash:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/outline/
    - assets/icons/bold/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "FFFFFF"
  image: "assets/logo.png"
  android: true
  ios: true
  android_disable_fullscreen: true
